# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: deb5ea11c8da02a176df03babbf6a12e418fecabb0afae7b2b66748899ca118295ac33e6fdd1c1d5ee5aa56890c89dce926f40edbdb6a6729bda14c7fadb83b3

test:
  secret_key_base: fe4d23a9df6edd2e08a313c203ae896bee3390cc0958b6d4e0ac0600c0ca006f463c238cd77b465def803ae163ab689fae296c476c53bec665601b2459c27a34

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
